"""empty message

Revision ID: 44c714f0446b
Revises: 
Create Date: 2021-12-06 23:34:13.795276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c714f0446b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alloys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('si', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('mn', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('p', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('s', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('ni', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('cr', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('mo', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('cu', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('v', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('al', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('n', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('nt', sa.Numeric(precision=2, scale=4), nullable=False),
    sa.Column('temp', sa.Integer(), nullable=False),
    sa.Column('tensile', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('yield_', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('elongation', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reduction', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alloys_al'), 'alloys', ['al'], unique=False)
    op.create_index(op.f('ix_alloys_c'), 'alloys', ['c'], unique=False)
    op.create_index(op.f('ix_alloys_cr'), 'alloys', ['cr'], unique=False)
    op.create_index(op.f('ix_alloys_cu'), 'alloys', ['cu'], unique=False)
    op.create_index(op.f('ix_alloys_elongation'), 'alloys', ['elongation'], unique=False)
    op.create_index(op.f('ix_alloys_mn'), 'alloys', ['mn'], unique=False)
    op.create_index(op.f('ix_alloys_mo'), 'alloys', ['mo'], unique=False)
    op.create_index(op.f('ix_alloys_n'), 'alloys', ['n'], unique=False)
    op.create_index(op.f('ix_alloys_ni'), 'alloys', ['ni'], unique=False)
    op.create_index(op.f('ix_alloys_nt'), 'alloys', ['nt'], unique=False)
    op.create_index(op.f('ix_alloys_p'), 'alloys', ['p'], unique=False)
    op.create_index(op.f('ix_alloys_reduction'), 'alloys', ['reduction'], unique=False)
    op.create_index(op.f('ix_alloys_s'), 'alloys', ['s'], unique=False)
    op.create_index(op.f('ix_alloys_si'), 'alloys', ['si'], unique=False)
    op.create_index(op.f('ix_alloys_temp'), 'alloys', ['temp'], unique=False)
    op.create_index(op.f('ix_alloys_tensile'), 'alloys', ['tensile'], unique=False)
    op.create_index(op.f('ix_alloys_v'), 'alloys', ['v'], unique=False)
    op.create_index(op.f('ix_alloys_yield_'), 'alloys', ['yield_'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alloys_yield_'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_v'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_tensile'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_temp'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_si'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_s'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_reduction'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_p'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_nt'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_ni'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_n'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_mo'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_mn'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_elongation'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_cu'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_cr'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_c'), table_name='alloys')
    op.drop_index(op.f('ix_alloys_al'), table_name='alloys')
    op.drop_table('alloys')
    # ### end Alembic commands ###
